spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micros
    driverClassName: org.postgresql.Driver
    username: micro
    password: Micro123
  sql:
    init:
      mode: always


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users_scheme


