spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:micros}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:micro}
    password: ${DB_PASSWORD:Micro123}
  sql:
    init:
      mode: always


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users_scheme


