spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:micros}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:micro}
    password: ${DB_PASSWORD:Micro123}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users_scheme

  liquibase:
    enabled: true
    drop-first: ${IS_DROP_FIRST:true}
    default-schema: users_scheme
    change-log: classpath:db/changelog/changelog-master.xml

